theme: jekyll-agency
url: ''
baseurl: ''
title: Your Awesome Website
email: your-email@example.com
description: Site description
author: Your Name
locale: en-US
analytics:
  google: null
collections:
  portfolio: null
markdown: kramdown
