theme: jekyll-agency
url: ''
baseurl: ''
title: Salonkaa
email: your-email@example.com
description: Site description
author: Wojciech Sobczyk
locale: en-US
analytics:
  google: null
collections:
  portfolio: null
markdown: kramdown
